#############################################################################
# Makefile for building: PiClock.app/Contents/MacOS/PiClock
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  PiClock.pro
# Template: app
# Command: /Users/johann/Qt/5.9.1/clang_64/bin/qmake -o Makefile PiClock.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++0x -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.9.1/clang_64/mkspecs/macx-clang -F/Users/johann/Qt/5.9.1/clang_64/lib
QMAKE         = /Users/johann/Qt/5.9.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/johann/Qt/5.9.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/johann/Qt/5.9.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PiClock1.0.0
DISTDIR = /Users/johann/Development/Qt/PiClock/.tmp/PiClock1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/johann/Qt/5.9.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/johann/Qt/5.9.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtWebSockets -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		weekdaybutton.cpp \
		musicplayer.cpp \
		volumeknobthread.cpp \
		mopidyreader.cpp \
		scrolltext.cpp \
		alarmsettings.cpp qrc_resourses.cpp \
		moc_mainwindow.cpp \
		moc_weekdaybutton.cpp \
		moc_musicplayer.cpp \
		moc_volumeknobthread.cpp \
		moc_mopidyreader.cpp \
		moc_scrolltext.cpp \
		moc_alarmsettings.cpp
OBJECTS       = main.o \
		mainwindow.o \
		weekdaybutton.o \
		musicplayer.o \
		volumeknobthread.o \
		mopidyreader.o \
		scrolltext.o \
		alarmsettings.o \
		qrc_resourses.o \
		moc_mainwindow.o \
		moc_weekdaybutton.o \
		moc_musicplayer.o \
		moc_volumeknobthread.o \
		moc_mopidyreader.o \
		moc_scrolltext.o \
		moc_alarmsettings.o
DIST          = ../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		PiClock.pro mainwindow.h \
		weekdaybutton.h \
		musicplayer.h \
		volumeknobthread.h \
		mopidyreader.h \
		scrolltext.h \
		alarmsettings.h main.cpp \
		mainwindow.cpp \
		weekdaybutton.cpp \
		musicplayer.cpp \
		volumeknobthread.cpp \
		mopidyreader.cpp \
		scrolltext.cpp \
		alarmsettings.cpp
QMAKE_TARGET  = PiClock
DESTDIR       = 
TARGET        = PiClock.app/Contents/MacOS/PiClock

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_musicplayer.h ui_alarmsettings.h $(OBJECTS)  
	@test -d PiClock.app/Contents/MacOS/ || mkdir -p PiClock.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PiClock.pro ../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		PiClock.pro \
		resourses.qrc \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.9.1/clang_64/lib/QtWebSockets.framework/QtWebSockets.prl \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PiClock.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf:
PiClock.pro:
resourses.qrc:
../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.9.1/clang_64/lib/QtWebSockets.framework/QtWebSockets.prl:
../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PiClock.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

PiClock.app/Contents/PkgInfo: 
	@test -d PiClock.app/Contents || mkdir -p PiClock.app/Contents
	@$(DEL_FILE) PiClock.app/Contents/PkgInfo
	@echo "APPL????" > PiClock.app/Contents/PkgInfo
PiClock.app/Contents/Resources/empty.lproj: 
	@test -d PiClock.app/Contents/Resources || mkdir -p PiClock.app/Contents/Resources
	@touch PiClock.app/Contents/Resources/empty.lproj
	
PiClock.app/Contents/Info.plist: 
	@test -d PiClock.app/Contents || mkdir -p PiClock.app/Contents
	@$(DEL_FILE) PiClock.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.BLochmann.PiClock,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PiClock,g" -e "s,@LIBRARY@,PiClock,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/Info.plist.app >PiClock.app/Contents/Info.plist

all: Makefile \
		PiClock.app/Contents/PkgInfo \
		PiClock.app/Contents/Resources/empty.lproj \
		PiClock.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resourses.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h weekdaybutton.h musicplayer.h volumeknobthread.h mopidyreader.h scrolltext.h alarmsettings.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp weekdaybutton.cpp musicplayer.cpp volumeknobthread.cpp mopidyreader.cpp scrolltext.cpp alarmsettings.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui musicplayer.ui alarmsettings.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r PiClock.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resourses.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resourses.cpp
qrc_resourses.cpp: resourses.qrc \
		../../../Qt/5.9.1/clang_64/bin/rcc \
		kurt_face.jpg \
		kurt_nala.jpg \
		kurt.jpg \
		loud_sound.png \
		image.png \
		weatherIcons/02n.png \
		weatherIcons/50n.png \
		weatherIcons/10d.png \
		weatherIcons/11n.png \
		weatherIcons/01n.png \
		weatherIcons/10n.png \
		weatherIcons/04d.png \
		weatherIcons/13d.png \
		weatherIcons/03d.png \
		weatherIcons/09d.png \
		weatherIcons/04n.png \
		weatherIcons/50d.png \
		weatherIcons/02d.png \
		weatherIcons/13n.png \
		weatherIcons/03n.png \
		weatherIcons/09n.png \
		weatherIcons/11d.png \
		weatherIcons/01d.png
	/Users/johann/Qt/5.9.1/clang_64/bin/rcc -name resourses resourses.qrc -o qrc_resourses.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -std=c++0x -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_weekdaybutton.cpp moc_musicplayer.cpp moc_volumeknobthread.cpp moc_mopidyreader.cpp moc_scrolltext.cpp moc_alarmsettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_weekdaybutton.cpp moc_musicplayer.cpp moc_volumeknobthread.cpp moc_mopidyreader.cpp moc_scrolltext.cpp moc_alarmsettings.cpp
moc_mainwindow.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mopidyreader.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		mainwindow.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_weekdaybutton.cpp: ../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		weekdaybutton.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib weekdaybutton.h -o moc_weekdaybutton.cpp

moc_musicplayer.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		volumeknobthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		musicplayer.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib musicplayer.h -o moc_musicplayer.cpp

moc_volumeknobthread.cpp: ../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		volumeknobthread.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib volumeknobthread.h -o moc_volumeknobthread.cpp

moc_mopidyreader.cpp: ../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mopidyreader.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib mopidyreader.h -o moc_mopidyreader.cpp

moc_scrolltext.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QStaticText \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		scrolltext.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib scrolltext.h -o moc_scrolltext.cpp

moc_alarmsettings.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		alarmsettings.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/johann/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/johann/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/johann/Development/Qt/PiClock -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtWebSockets.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/johann/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/johann/Qt/5.9.1/clang_64/lib alarmsettings.h -o moc_alarmsettings.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_musicplayer.h ui_alarmsettings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_musicplayer.h ui_alarmsettings.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.9.1/clang_64/bin/uic \
		musicplayer.h \
		scrolltext.h \
		alarmsettings.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		volumeknobthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QStaticText \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h
	/Users/johann/Qt/5.9.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_musicplayer.h: musicplayer.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/johann/Qt/5.9.1/clang_64/bin/uic musicplayer.ui -o ui_musicplayer.h

ui_alarmsettings.h: alarmsettings.ui \
		../../../Qt/5.9.1/clang_64/bin/uic \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h
	/Users/johann/Qt/5.9.1/clang_64/bin/uic alarmsettings.ui -o ui_alarmsettings.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mopidyreader.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QHostInfo \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qhostinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mopidyreader.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		ui_mainwindow.h \
		alarmsettings.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		musicplayer.h \
		volumeknobthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		scrolltext.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QStaticText \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

weekdaybutton.o: weekdaybutton.cpp weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o weekdaybutton.o weekdaybutton.cpp

musicplayer.o: musicplayer.cpp musicplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		volumeknobthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		ui_musicplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		WiringPi/wiringPi/wiringPi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o musicplayer.o musicplayer.cpp

volumeknobthread.o: volumeknobthread.cpp volumeknobthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		WiringPi/wiringPi/wiringPi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o volumeknobthread.o volumeknobthread.cpp

mopidyreader.o: mopidyreader.cpp mopidyreader.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/QHostInfo \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers/qhostinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mopidyreader.o mopidyreader.cpp

scrolltext.o: scrolltext.cpp scrolltext.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QStaticText \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scrolltext.o scrolltext.cpp

alarmsettings.o: alarmsettings.cpp alarmsettings.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		weekdaybutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QSplitter \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		ui_alarmsettings.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTime \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alarmsettings.o alarmsettings.cpp

qrc_resourses.o: qrc_resourses.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resourses.o qrc_resourses.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_weekdaybutton.o: moc_weekdaybutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_weekdaybutton.o moc_weekdaybutton.cpp

moc_musicplayer.o: moc_musicplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_musicplayer.o moc_musicplayer.cpp

moc_volumeknobthread.o: moc_volumeknobthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_volumeknobthread.o moc_volumeknobthread.cpp

moc_mopidyreader.o: moc_mopidyreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mopidyreader.o moc_mopidyreader.cpp

moc_scrolltext.o: moc_scrolltext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scrolltext.o moc_scrolltext.cpp

moc_alarmsettings.o: moc_alarmsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alarmsettings.o moc_alarmsettings.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

